import matplotlib.pyplot as plt

file = open(f'C:/collatz/data/output/10k.txt', 'r')
file1 = open(f'C:/collatz/data/output/20k.txt', 'r')
file2 = open(f'C:/collatz/data/output/30k.txt', 'r')
file3 = open(f'C:/collatz/data/output/40k.txt', 'r')
file4 = open(f'C:/collatz/data/output/50k.txt', 'r')
file5 = open(f'C:/collatz/data/output/60k.txt', 'r')
file6 = open(f'C:/collatz/data/output/70k.txt', 'r')
file7 = open(f'C:/collatz/data/output/80k.txt', 'r')
file8 = open(f'C:/collatz/data/output/90k.txt', 'r')
file9 = open(f'C:/collatz/data/output/100k.txt', 'r')

string = file.readline()
string1 = file1.readline()
string2 = file2.readline()
string3 = file3.readline()
string4 = file4.readline()
string5 = file5.readline()
string6 = file6.readline()
string7 = file7.readline()
string8 = file8.readline()
string9 = file9.readline()

string = eval(string)
string1 = eval(string1)
string2 = eval(string2)
string3 = eval(string3)
string4 = eval(string4)
string5 = eval(string5)
string6 = eval(string6)
string7 = eval(string7)
string8 = eval(string8)
string9 = eval(string9)

lists = sorted(string.items())
lists1 = sorted(string1.items())
lists2 = sorted(string2.items())
lists3 = sorted(string3.items())
lists4 = sorted(string4.items())
lists5 = sorted(string5.items())
lists6 = sorted(string6.items())
lists7 = sorted(string7.items())
lists8 = sorted(string8.items())
lists9 = sorted(string9.items())

x, y = zip(*lists)
l, n = zip(*lists1)
k, p = zip(*lists2)
r, t = zip(*lists3)
q, w = zip(*lists4)
z, e = zip(*lists5)
m, o = zip(*lists6)
j, g = zip(*lists7)
u, b = zip(*lists8)
c, a = zip(*lists9)

fig = plt.figure()
ax = fig.add_subplot(111)

ax.plot(x, y, label = '10k')
ax.plot(l, n, label = '20k')
ax.plot(k, p, label = '30k')
ax.plot(r, t, label = '40k')
ax.plot(q, w, label = '50k')
ax.plot(z, e, label = '60k')
ax.plot(m, o, label = '70k')
ax.plot(j, g, label = '80k')
ax.plot(u, b, label = '90k')
ax.plot(c, a, color = "red", label = '100k')

ax.legend()

plt.show()